-- This file was automatically generated by https://github.com/HerrNamenlos123/allegro5-build

ALLEGRO5_INCLUDE_DIRS = { _SCRIPT_DIR .. "/include", _SCRIPT_DIR .. "/src" }

ALLEGRO5_LINK_DIRS = { _SCRIPT_DIR .. "/lib/" }

ALLEGRO5_LINKS = { "allegro_monolith-static", "freetype", "libpng", "zlib" }
