-- This file was automatically generated by https://github.com/HerrNamenlos123/allegro5-build

ALLEGRO5_INCLUDE_DIRS = { "F:/Users/Florian/Documents/VS-Projects/allegro5-build/include", "F:/Users/Florian/Documents/VS-Projects/allegro5-build/src" }

ALLEGRO5_LINK_DIRS = { "F:/Users/Florian/Documents/VS-Projects/allegro5-build/bin/", "F:/Users/Florian/Documents/VS-Projects/allegro5-build/modules/freetype/bin/", "F:/Users/Florian/Documents/VS-Projects/allegro5-build/modules/libpng/bin/", "F:/Users/Florian/Documents/VS-Projects/allegro5-build/modules/zlib/bin/" }

ALLEGRO5_LINKS = { "allegro_monolith-static", "freetype", "libpng", "zlib" }
